### ISSUE TITLE
Find week/1 searches for this week instead of next week

### ISSUE THREAD

**Issue by MightyCupcakes** [CS2103AUG2016-F10-C2/main#151]

**Comment by tanboonjoon** [comment]
@MightyCupcakes  i look at the test case.
The list contain the following values
list.get(0) --> 2016-10-23T23:59
list.get(1) --> 2016-10-23T23:59
list.get(2) --> 2016-10-23T23:59
list.get(3) --> 2016-10-24T20:22:01.451
list.get(4) --> 2016-10-31T20:22:01.452

and the following code was commented out :
assertFindResult("find week/1", list.get(4) );

find week/ is set to filter out the task found in that particular week. a week is defined from Monday to Sunday . regardless of what day today is. if today is  Sunday, tomorrow which is Monday is still considered 'next week' 
which is why find week/1 will display list.get(3) instead of list.get(4) ?
